name: dev-to-do-worflow

on:
  pull_request:
    types:
      - closed
    branches:  main
  workflow_dispatch:

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: to-do-repo
      IMAGE_NAME: to-do-application
    
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
    
    - name: Build Docker Image
      run:
        docker build . --tag $DOCKER_REPOSITORY/$IMAGE_NAME --no-cache

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_REPOSITORY_PASSWORD }}" | docker login -u $DOCKER_REPOSITORY --password-stdin
  
    - name: Push Image to Docker Hub
      run:
        docker push $DOCKER_REPOSITORY/$IMAGE_NAME